[images]
  remote_images = ["https://.*"]

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.0.0"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"

# Improve mobile caching behavior
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Improve mobile PWA support
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[plugins]]
  package = "@netlify/plugin-nextjs"
